### ISSUE TITLE
Sample pipeline 

### ISSUE THREAD

**Issue by bxffour** [Joe-Degs/resume#1]
Here is a possible github workflow file for your project:

```yaml
# This is a basic workflow to compile latex files to pdf and deploy to a site

name: Latex Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job compiles the latex files to pdf using xu action
  compile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Uses xu action to compile latex files to pdf
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2.1.0
        with:
          root_file: main.tex

      # Uploads the pdf file as an artifact for later use
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: output-pdf
          path: main.pdf

  # This job deploys the pdf file to a site using some deployment action (you need to replace this with your actual deployment action and inputs)
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # This job needs the compile job to finish successfully before running
    needs: compile

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Downloads the pdf file from the artifact store 
      - name: Download PDF from artifact store 
        uses: actions/download-artifact@v2.1.0 
        with:
          name: output-pdf 

      # Deploys the pdf file to a site using some deployment action (you need to replace this with your actual deployment action and inputs)
      - name: Deploy PDF to site 
        uses: some-deployment-action@some-version 
        with:
          some-inputs-for-the-deployment-action 
```
